// <auto-generated />
using System;
using Clouud.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Clouud.Web.Data.Migrations
{
    [DbContext(typeof(BancoDados))]
    [Migration("20260925191851_ListaDesejos")]
    partial class ListaDesejos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Clouud.Web.Models.CarrinhoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdicionadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("adicionado_em");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_carrinho_itens");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_carrinho_itens_produto_id");

                    b.HasIndex("UsuarioId", "ProdutoId")
                        .IsUnique()
                        .HasDatabaseName("ix_carrinho_itens_usuario_id_produto_id");

                    b.ToTable("carrinho_itens", t =>
                        {
                            t.HasCheckConstraint("ck_carrinho_itens_quantidade", "quantidade BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("Clouud.Web.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nome");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_categorias_slug");

                    b.ToTable("categorias");
                });

            modelBuilder.Entity("Clouud.Web.Models.Chave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdicionadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("adicionada_em");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("codigo");

                    b.Property<int?>("PedidoItemId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_item_id");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("VendidaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vendida_em");

                    b.HasKey("Id")
                        .HasName("pk_chaves");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_chaves_codigo");

                    b.HasIndex("PedidoItemId")
                        .HasDatabaseName("ix_chaves_pedido_item_id");

                    b.HasIndex("ProdutoId", "Status")
                        .HasDatabaseName("ix_chaves_produto_id_status");

                    b.ToTable("chaves", t =>
                        {
                            t.HasCheckConstraint("ck_chaves_pedido", "(status IN ('Reservada', 'Vendida') AND pedido_item_id IS NOT NULL) OR (status = 'Disponivel' AND pedido_item_id IS NULL) OR status = 'Inativa'");

                            t.HasCheckConstraint("ck_chaves_status", "status IN ('Disponivel', 'Reservada', 'Vendida', 'Inativa')");
                        });
                });

            modelBuilder.Entity("Clouud.Web.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_empresas");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_empresas_slug");

                    b.ToTable("empresas");
                });

            modelBuilder.Entity("Clouud.Web.Models.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Capa")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("capa");

                    b.Property<string>("ClassificacaoIndicativa")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("classificacao_indicativa");

                    b.Property<DateOnly?>("DataLancamento")
                        .HasColumnType("date")
                        .HasColumnName("data_lancamento");

                    b.Property<string>("Descricao")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("descricao");

                    b.Property<int?>("DesenvolvedoraId")
                        .HasColumnType("integer")
                        .HasColumnName("desenvolvedora_id");

                    b.Property<bool>("Destaque")
                        .HasColumnType("boolean")
                        .HasColumnName("destaque");

                    b.Property<int?>("PublicadoraId")
                        .HasColumnType("integer")
                        .HasColumnName("publicadora_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("slug");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("pk_jogos");

                    b.HasIndex("DesenvolvedoraId")
                        .HasDatabaseName("ix_jogos_desenvolvedora_id");

                    b.HasIndex("PublicadoraId")
                        .HasDatabaseName("ix_jogos_publicadora_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_jogos_slug");

                    b.ToTable("jogos");
                });

            modelBuilder.Entity("Clouud.Web.Models.ListaDesejo", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<int>("JogoId")
                        .HasColumnType("integer")
                        .HasColumnName("jogo_id");

                    b.Property<DateTime>("AdicionadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("adicionado_em");

                    b.HasKey("UsuarioId", "JogoId")
                        .HasName("pk_lista_desejos");

                    b.HasIndex("JogoId")
                        .HasDatabaseName("ix_lista_desejos_jogo_id");

                    b.ToTable("lista_desejos");
                });

            modelBuilder.Entity("Clouud.Web.Models.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoTransacao")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("codigo_transacao");

                    b.Property<DateTime?>("ConfirmadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("metodo");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_pagamentos");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("ix_pagamentos_pedido_id");

                    b.ToTable("pagamentos", t =>
                        {
                            t.HasCheckConstraint("ck_pagamentos_metodo", "metodo IN ('Pix', 'Cartao', 'Boleto')");

                            t.HasCheckConstraint("ck_pagamentos_status", "status IN ('Pendente', 'Aprovado', 'Recusado')");
                        });
                });

            modelBuilder.Entity("Clouud.Web.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("PagarAte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pagar_ate");

                    b.Property<DateTime?>("PagoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pago_em");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_pedidos");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_pedidos_usuario_id");

                    b.HasIndex("Status", "PagarAte")
                        .HasDatabaseName("ix_pedidos_status_pagar_ate");

                    b.ToTable("pedidos", t =>
                        {
                            t.HasCheckConstraint("ck_pedidos_status", "status IN ('AguardandoPagamento', 'Pago', 'Cancelado', 'Reembolsado')");

                            t.HasCheckConstraint("ck_pedidos_total", "total >= 0");
                        });
                });

            modelBuilder.Entity("Clouud.Web.Models.PedidoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco_unitario");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("Id")
                        .HasName("pk_pedido_itens");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_pedido_itens_produto_id");

                    b.HasIndex("PedidoId", "ProdutoId")
                        .IsUnique()
                        .HasDatabaseName("ix_pedido_itens_pedido_id_produto_id");

                    b.ToTable("pedido_itens", t =>
                        {
                            t.HasCheckConstraint("ck_pedido_itens_quantidade", "quantidade > 0");

                            t.HasCheckConstraint("ck_pedido_itens_valores", "preco_unitario >= 0 AND subtotal >= 0");
                        });
                });

            modelBuilder.Entity("Clouud.Web.Models.Plataforma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<string>("InstrucoesAtivacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("instrucoes_ativacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nome");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_plataformas");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_plataformas_slug");

                    b.ToTable("plataformas");
                });

            modelBuilder.Entity("Clouud.Web.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Edicao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("edicao");

                    b.Property<int>("JogoId")
                        .HasColumnType("integer")
                        .HasColumnName("jogo_id");

                    b.Property<int>("PlataformaId")
                        .HasColumnType("integer")
                        .HasColumnName("plataforma_id");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco");

                    b.Property<decimal?>("PrecoPromocional")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco_promocional");

                    b.Property<DateOnly?>("PromocaoAte")
                        .HasColumnType("date")
                        .HasColumnName("promocao_ate");

                    b.Property<string>("Regiao")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("regiao");

                    b.HasKey("Id")
                        .HasName("pk_produtos");

                    b.HasIndex("PlataformaId")
                        .HasDatabaseName("ix_produtos_plataforma_id");

                    b.HasIndex("JogoId", "PlataformaId", "Edicao")
                        .IsUnique()
                        .HasDatabaseName("ix_produtos_jogo_id_plataforma_id_edicao");

                    b.ToTable("produtos", t =>
                        {
                            t.HasCheckConstraint("ck_produtos_preco", "preco >= 0");

                            t.HasCheckConstraint("ck_produtos_preco_promocional", "preco_promocional IS NULL OR (preco_promocional >= 0 AND preco_promocional < preco)");
                        });
                });

            modelBuilder.Entity("Clouud.Web.Models.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Foto")
                        .HasColumnType("text")
                        .HasColumnName("foto");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer")
                        .HasColumnName("perfil");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("senha");

                    b.HasKey("ID")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("JogoCategorias", b =>
                {
                    b.Property<int>("JogoId")
                        .HasColumnType("integer")
                        .HasColumnName("jogo_id");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.HasKey("JogoId", "CategoriaId")
                        .HasName("pk_jogo_categorias");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_jogo_categorias_categoria_id");

                    b.ToTable("jogo_categorias");
                });

            modelBuilder.Entity("Clouud.Web.Models.CarrinhoItem", b =>
                {
                    b.HasOne("Clouud.Web.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_carrinho_itens_produtos_produto_id");

                    b.HasOne("Clouud.Web.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_carrinho_itens_usuarios_usuario_id");

                    b.Navigation("Produto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Clouud.Web.Models.Chave", b =>
                {
                    b.HasOne("Clouud.Web.Models.PedidoItem", "PedidoItem")
                        .WithMany("Chaves")
                        .HasForeignKey("PedidoItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_chaves_pedido_itens_pedido_item_id");

                    b.HasOne("Clouud.Web.Models.Produto", "Produto")
                        .WithMany("Chaves")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_chaves_produtos_produto_id");

                    b.Navigation("PedidoItem");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Clouud.Web.Models.Jogo", b =>
                {
                    b.HasOne("Clouud.Web.Models.Empresa", "Desenvolvedora")
                        .WithMany()
                        .HasForeignKey("DesenvolvedoraId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_jogos_empresas_desenvolvedora_id");

                    b.HasOne("Clouud.Web.Models.Empresa", "Publicadora")
                        .WithMany()
                        .HasForeignKey("PublicadoraId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_jogos_empresas_publicadora_id");

                    b.Navigation("Desenvolvedora");

                    b.Navigation("Publicadora");
                });

            modelBuilder.Entity("Clouud.Web.Models.ListaDesejo", b =>
                {
                    b.HasOne("Clouud.Web.Models.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lista_desejos_jogos_jogo_id");

                    b.HasOne("Clouud.Web.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lista_desejos_usuarios_usuario_id");

                    b.Navigation("Jogo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Clouud.Web.Models.Pagamento", b =>
                {
                    b.HasOne("Clouud.Web.Models.Pedido", "Pedido")
                        .WithMany("Pagamentos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pagamentos_pedidos_pedido_id");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Clouud.Web.Models.Pedido", b =>
                {
                    b.HasOne("Clouud.Web.Models.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedidos_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Clouud.Web.Models.PedidoItem", b =>
                {
                    b.HasOne("Clouud.Web.Models.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_itens_pedidos_pedido_id");

                    b.HasOne("Clouud.Web.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_itens_produtos_produto_id");

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Clouud.Web.Models.Produto", b =>
                {
                    b.HasOne("Clouud.Web.Models.Jogo", "Jogo")
                        .WithMany("Produtos")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_produtos_jogos_jogo_id");

                    b.HasOne("Clouud.Web.Models.Plataforma", "Plataforma")
                        .WithMany("Produtos")
                        .HasForeignKey("PlataformaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_produtos_plataformas_plataforma_id");

                    b.Navigation("Jogo");

                    b.Navigation("Plataforma");
                });

            modelBuilder.Entity("JogoCategorias", b =>
                {
                    b.HasOne("Clouud.Web.Models.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jogo_categorias_categorias_categoria_id");

                    b.HasOne("Clouud.Web.Models.Jogo", null)
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jogo_categorias_jogos_jogo_id");
                });

            modelBuilder.Entity("Clouud.Web.Models.Jogo", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Clouud.Web.Models.Pedido", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("Clouud.Web.Models.PedidoItem", b =>
                {
                    b.Navigation("Chaves");
                });

            modelBuilder.Entity("Clouud.Web.Models.Plataforma", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Clouud.Web.Models.Produto", b =>
                {
                    b.Navigation("Chaves");
                });

            modelBuilder.Entity("Clouud.Web.Models.Usuario", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
